### ISSUE TITLE
Mikrotik RouterOS Setup

### ISSUE THREAD

**Issue by achmatch** [dns-sb/DoH#1]
Hello,

Im using dns.sb on some device, but i dont know how to setup dns.sb on mikrotik RouterOS with DNS Over HTTPS?

**Comment by Showfom** [comment]
https://help.mikrotik.com/docs/pages/viewpage.action?pageId=83099652

You might need to obtain a certificate from Sectigo, Let's Encrypt, and Google Trust Services.

https://www.sectigo.com/knowledge-base/detail/Sectigo-Root-Certificates/kA03l000000c4KV
https://letsencrypt.org/certificates/
https://pki.goog/repository/

Unfortunately, I don't have RouterOS and therefore can't assist you with testing.
